### Login
POST http://localhost:8000/faskes/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "12345"
}

### Rumah Sakit
GET http://localhost/faskes/rumahsakit?page=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4NTUxMzk4OCwiZXhwIjoxNjg1NTE0ODg4fQ.hSwKx52UNZp0Zh3LTwXpLnQhx7uvVObodnCARPidlfM

### Rumah Sakit Specified
GET http://localhost/faskes/rumahsakit/3372253
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MzY5MDYzOCwiZXhwIjoxNjgzNjkxNTM4fQ.JBtwAB6xXxwG65Jq8vDw4dWX7Wr4l6_oL7Bq6EBbwis


### Praktek Mandiri
GET http://192.168.49.40:8000/faskes/praktekmandiri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko

### Show Praktek Mandiri
GET http://192.168.49.40:8000/faskes/praktekmandiri/11010100006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko

### Praktek Mandiri Review
POST http://localhost:8000/faskes/praktekmandirireview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4NTkzOTE3MywiZXhwIjoxNjg1OTQwMDczfQ.KBWNbsLoOTYk9EMY6k_5RLvUf0FgMGeMXGxCyWt4lr4

{
    "doctor": {
        "fasyankes_code": "36740100AAA",
        "nik": "1234567890",
        "str_code": "212118181383",
        "health_worker_name": "dr. Ujang",
        "specialization": "Dokter Hewan"
    },
    "info": {
        "checkin-time": "2021-01-01T00:00:00Z",
        "review-time": "2021-01-01T02:00:00Z",
        "visit-date": "2021-01-02"
    },
    "result": {
        "resultDescription": "Puas",
        "resultPoint": 1
    },
    "userId": "1",
    "reviews": [
        {
            "code": "question-01",
            "aspect": "ketepatan Waktu",
            "questionDescription": "Dokter buka praktik seperti jadwal yang ditentukan",
            "answer": "Tidak",
            "answerPoint": 1
        },
        {
            "code": "question-02",
            "aspect": "informasi yang diberikan dokter",
            "questionDescription": "Dokter memberikan edukasi terkait penyakit yang diderita",
            "answer": "Ya",
            "answerPoint": 1 
        },
        {
            "code": "question-03",
            "aspect": "pelayanan yang diberikan dokter",
            "questionDescription": "Dokter memberikan penjelasan dan meminta persetujuan saya dalam pelayanan kesehatan",
            "answer": "Ya",
            "answerPoint": 1 
        },
        {
            "code": "question-04",
            "aspect": "penilaian kebersihan TPMD/TPMDG",
            "questionDescription": "Kebersihan ruang tunggu dan ruang periksa",
            "answer": "Ya",
            "answerPoint": 1
        }
    ]
}

### Klinik
GET  http://localhost:5000/klinik?page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5NjYzMiwiZXhwIjoxNjgyMzk3NTMyfQ.64Xi4BmYzO_amr-qPIs3c9d85ZVpMadXR8-jvqg3Xbg

### Show Klinik
GET http://localhost:5000/klinik/11080300006

### LabKes
GET http://localhost:5000/labkes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show LabKes
GET http://localhost:5000/labkes/11040700001

### UTD
GET http://localhost:5000/utd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show UTD
GET http://localhost:5000/utd/11010600001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Praktek Mandiri Nakes
GET http://192.168.49.40:8000/faskes/praktekmandirinakes?praktekMandiriId=11020100001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko