### Login
POST http://localhost:8000/faskes/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### Rumah Sakit
GET http://192.168.49.40:8000/faskes/rumahsakit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTY2NSwiZXhwIjoxNjgyNzUyNTY1fQ._qHWI9BpA-1pugB9cRH7GWubmY7mqPhy3XpN-3ewrCQ


### Praktek Mandiri
GET http://192.168.49.40:8000/faskes/praktekmandiri
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko

### Show Praktek Mandiri
GET http://192.168.49.40:8000/faskes/praktekmandiri/11010100006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko

### Praktek Mandiri Review
POST http://localhost:8000/faskes/praktekmandirireview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjkxNTYxOCwiZXhwIjoxNjgyOTE2NTE4fQ.BVkaqvABnqXzqhBh5464lnYIDhfpcd9H5dtozveXPkc

{
    "doctor": {
        "fasyankes_code": "36740100AAA",
        "str_code": "212118181383",
        "health_worker_name": "dr. Ujang",
        "specialization": "Dokter Hewan"
    },
    "info": {
        "checkin-time": "2021-01-01T00:00:00Z",
        "review-time": "2021-01-01T02:00:00Z"
    },
    "reviews": [
        {
            "question": "Ketepatan Waktu",
            "description": "Kesesuaian waktu pelayanan dengan jadwal praktik",
            "answer": "Tepat Waktu"
        },
        {
            "question": "Komunikasi",
            "description": "Kualitas informasi yang disampaikan pada Anda",
            "answer": "Mudah Dipahami"
        },
        {
            "question": "Kebersihan",
            "description": "Kebersihan tempat dan peralatan",
            "answer": "Bersih"
        },
        {
            "question": "Pelayanan",
            "description": "Keseluruhan pelayanan dokter",
            "answer": "Bersih"
        }
    ]
}

### Klinik
GET  http://localhost:5000/klinik?page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5NjYzMiwiZXhwIjoxNjgyMzk3NTMyfQ.64Xi4BmYzO_amr-qPIs3c9d85ZVpMadXR8-jvqg3Xbg

### Show Klinik
GET http://localhost:5000/klinik/11080300006

### LabKes
GET http://localhost:5000/labkes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show LabKes
GET http://localhost:5000/labkes/11040700001

### UTD
GET http://localhost:5000/utd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show UTD
GET http://localhost:5000/utd/11010600001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Praktek Mandiri Nakes
GET http://192.168.49.40:8000/faskes/praktekmandirinakes?praktekMandiriId=11020100001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4Mjc1MTMxMSwiZXhwIjoxNjgyNzUyMjExfQ.sTmu0JAVsyERMQrBRlCfDguik-M92_zlT396ZxgOpko