### Login
POST http://localhost/faskes/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### Rumah Sakit
GET http://localhost/faskes/rumahsakit


### Praktek Mandiri
GET http://localhost/faskes/praktekmandiri?nama=DOKTER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjYwMjkxOCwiZXhwIjoxNjgyNjAzODE4fQ.vivLZdIa2-4pdtLVCuI9avGx9IdFkUzo2CpKYcUZvj8

### Show Praktek Mandiri
GET http://localhost:5000/faskes/praktekmandiri/11010100006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjYwMDY4NSwiZXhwIjoxNjgyNjAxNTg1fQ.4zn6U7EH_pdCnGa8dzJIRHjhRBP0s1HjJ6OCABpIuQk

### Klinik
GET  http://localhost:5000/klinik?page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5NjYzMiwiZXhwIjoxNjgyMzk3NTMyfQ.64Xi4BmYzO_amr-qPIs3c9d85ZVpMadXR8-jvqg3Xbg

### Show Klinik
GET http://localhost:5000/klinik/11080300006

### LabKes
GET http://localhost:5000/labkes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show LabKes
GET http://localhost:5000/labkes/11040700001

### UTD
GET http://localhost:5000/utd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Show UTD
GET http://localhost:5000/utd/11010600001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM5ODQzMywiZXhwIjoxNjgyMzk5MzMzfQ.iGHZc2U5dl3_TyakT1Dy6RVcR1FjNuK2B8F3dVv92zg

### Praktek Mandiri Nakes
GET http://localhost:5000/faskes/praktekmandirinakes?praktekMandiriId=11020100001